//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FE_SERVILLANTAS.WSServillantas {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.retail.efact/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.retail.efact/")]
    public partial class authorization : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string passwordField;
        
        private string userField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.retail.efact/")]
    public partial class transactionResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string identifierField;
        
        private string outStringField;
        
        private int responseCodeField;
        
        private string uuidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
                this.RaisePropertyChanged("identifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string outString {
            get {
                return this.outStringField;
            }
            set {
                this.outStringField = value;
                this.RaisePropertyChanged("outString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("responseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
                this.RaisePropertyChanged("uuid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.retail.efact/", ConfigurationName="WSServillantas.TransactionService")]
    public interface TransactionService {
        
        // CODEGEN: Generating message contract since message sendPingRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://service.retail.efact/TransactionService/sendPingRequest", ReplyAction="http://service.retail.efact/TransactionService/sendPingResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FE_SERVILLANTAS.WSServillantas.sendPingResponse sendPing(FE_SERVILLANTAS.WSServillantas.sendPingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.retail.efact/TransactionService/sendPingRequest", ReplyAction="http://service.retail.efact/TransactionService/sendPingResponse")]
        System.Threading.Tasks.Task<FE_SERVILLANTAS.WSServillantas.sendPingResponse> sendPingAsync(FE_SERVILLANTAS.WSServillantas.sendPingRequest request);
        
        // CODEGEN: Generating message contract since message sendDespatchAdviceRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://service.retail.efact/TransactionService/sendDespatchAdviceRequest", ReplyAction="http://service.retail.efact/TransactionService/sendDespatchAdviceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FE_SERVILLANTAS.WSServillantas.Exception), Action="http://service.retail.efact/TransactionService/sendDespatchAdvice/Fault/Exception" +
            "", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FE_SERVILLANTAS.WSServillantas.sendDespatchAdviceResponse sendDespatchAdvice(FE_SERVILLANTAS.WSServillantas.sendDespatchAdviceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.retail.efact/TransactionService/sendDespatchAdviceRequest", ReplyAction="http://service.retail.efact/TransactionService/sendDespatchAdviceResponse")]
        System.Threading.Tasks.Task<FE_SERVILLANTAS.WSServillantas.sendDespatchAdviceResponse> sendDespatchAdviceAsync(FE_SERVILLANTAS.WSServillantas.sendDespatchAdviceRequest request);
        
        // CODEGEN: Generating message contract since message sendInvoiceRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://service.retail.efact/TransactionService/sendInvoiceRequest", ReplyAction="http://service.retail.efact/TransactionService/sendInvoiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FE_SERVILLANTAS.WSServillantas.Exception), Action="http://service.retail.efact/TransactionService/sendInvoice/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FE_SERVILLANTAS.WSServillantas.sendInvoiceResponse sendInvoice(FE_SERVILLANTAS.WSServillantas.sendInvoiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.retail.efact/TransactionService/sendInvoiceRequest", ReplyAction="http://service.retail.efact/TransactionService/sendInvoiceResponse")]
        System.Threading.Tasks.Task<FE_SERVILLANTAS.WSServillantas.sendInvoiceResponse> sendInvoiceAsync(FE_SERVILLANTAS.WSServillantas.sendInvoiceRequest request);
        
        // CODEGEN: Generating message contract since message sendBoletaRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://service.retail.efact/TransactionService/sendBoletaRequest", ReplyAction="http://service.retail.efact/TransactionService/sendBoletaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FE_SERVILLANTAS.WSServillantas.Exception), Action="http://service.retail.efact/TransactionService/sendBoleta/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FE_SERVILLANTAS.WSServillantas.sendBoletaResponse sendBoleta(FE_SERVILLANTAS.WSServillantas.sendBoletaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.retail.efact/TransactionService/sendBoletaRequest", ReplyAction="http://service.retail.efact/TransactionService/sendBoletaResponse")]
        System.Threading.Tasks.Task<FE_SERVILLANTAS.WSServillantas.sendBoletaResponse> sendBoletaAsync(FE_SERVILLANTAS.WSServillantas.sendBoletaRequest request);
        
        // CODEGEN: Generating message contract since message sendCreditNoteRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://service.retail.efact/TransactionService/sendCreditNoteRequest", ReplyAction="http://service.retail.efact/TransactionService/sendCreditNoteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FE_SERVILLANTAS.WSServillantas.Exception), Action="http://service.retail.efact/TransactionService/sendCreditNote/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FE_SERVILLANTAS.WSServillantas.sendCreditNoteResponse sendCreditNote(FE_SERVILLANTAS.WSServillantas.sendCreditNoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.retail.efact/TransactionService/sendCreditNoteRequest", ReplyAction="http://service.retail.efact/TransactionService/sendCreditNoteResponse")]
        System.Threading.Tasks.Task<FE_SERVILLANTAS.WSServillantas.sendCreditNoteResponse> sendCreditNoteAsync(FE_SERVILLANTAS.WSServillantas.sendCreditNoteRequest request);
        
        // CODEGEN: Generating message contract since message sendDebitNoteRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://service.retail.efact/TransactionService/sendDebitNoteRequest", ReplyAction="http://service.retail.efact/TransactionService/sendDebitNoteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FE_SERVILLANTAS.WSServillantas.Exception), Action="http://service.retail.efact/TransactionService/sendDebitNote/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FE_SERVILLANTAS.WSServillantas.sendDebitNoteResponse sendDebitNote(FE_SERVILLANTAS.WSServillantas.sendDebitNoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.retail.efact/TransactionService/sendDebitNoteRequest", ReplyAction="http://service.retail.efact/TransactionService/sendDebitNoteResponse")]
        System.Threading.Tasks.Task<FE_SERVILLANTAS.WSServillantas.sendDebitNoteResponse> sendDebitNoteAsync(FE_SERVILLANTAS.WSServillantas.sendDebitNoteRequest request);
        
        // CODEGEN: Generating message contract since message sendVoidedDocumentRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://service.retail.efact/TransactionService/sendVoidedDocumentRequest", ReplyAction="http://service.retail.efact/TransactionService/sendVoidedDocumentResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FE_SERVILLANTAS.WSServillantas.sendVoidedDocumentResponse sendVoidedDocument(FE_SERVILLANTAS.WSServillantas.sendVoidedDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.retail.efact/TransactionService/sendVoidedDocumentRequest", ReplyAction="http://service.retail.efact/TransactionService/sendVoidedDocumentResponse")]
        System.Threading.Tasks.Task<FE_SERVILLANTAS.WSServillantas.sendVoidedDocumentResponse> sendVoidedDocumentAsync(FE_SERVILLANTAS.WSServillantas.sendVoidedDocumentRequest request);
        
        // CODEGEN: Generating message contract since message sendPerceptionRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://service.retail.efact/TransactionService/sendPerceptionRequest", ReplyAction="http://service.retail.efact/TransactionService/sendPerceptionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FE_SERVILLANTAS.WSServillantas.Exception), Action="http://service.retail.efact/TransactionService/sendPerception/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FE_SERVILLANTAS.WSServillantas.sendPerceptionResponse sendPerception(FE_SERVILLANTAS.WSServillantas.sendPerceptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.retail.efact/TransactionService/sendPerceptionRequest", ReplyAction="http://service.retail.efact/TransactionService/sendPerceptionResponse")]
        System.Threading.Tasks.Task<FE_SERVILLANTAS.WSServillantas.sendPerceptionResponse> sendPerceptionAsync(FE_SERVILLANTAS.WSServillantas.sendPerceptionRequest request);
        
        // CODEGEN: Generating message contract since message sendRetentionRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://service.retail.efact/TransactionService/sendRetentionRequest", ReplyAction="http://service.retail.efact/TransactionService/sendRetentionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FE_SERVILLANTAS.WSServillantas.Exception), Action="http://service.retail.efact/TransactionService/sendRetention/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FE_SERVILLANTAS.WSServillantas.sendRetentionResponse sendRetention(FE_SERVILLANTAS.WSServillantas.sendRetentionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.retail.efact/TransactionService/sendRetentionRequest", ReplyAction="http://service.retail.efact/TransactionService/sendRetentionResponse")]
        System.Threading.Tasks.Task<FE_SERVILLANTAS.WSServillantas.sendRetentionResponse> sendRetentionAsync(FE_SERVILLANTAS.WSServillantas.sendRetentionRequest request);
        
        // CODEGEN: Generating message contract since message getStatusRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://service.retail.efact/TransactionService/getStatusRequest", ReplyAction="http://service.retail.efact/TransactionService/getStatusResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FE_SERVILLANTAS.WSServillantas.getStatusResponse getStatus(FE_SERVILLANTAS.WSServillantas.getStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.retail.efact/TransactionService/getStatusRequest", ReplyAction="http://service.retail.efact/TransactionService/getStatusResponse")]
        System.Threading.Tasks.Task<FE_SERVILLANTAS.WSServillantas.getStatusResponse> getStatusAsync(FE_SERVILLANTAS.WSServillantas.getStatusRequest request);
        
        // CODEGEN: Generating message contract since message sendVoidedDocumentXmlRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://service.retail.efact/TransactionService/sendVoidedDocumentXmlRequest", ReplyAction="http://service.retail.efact/TransactionService/sendVoidedDocumentXmlResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FE_SERVILLANTAS.WSServillantas.sendVoidedDocumentXmlResponse sendVoidedDocumentXml(FE_SERVILLANTAS.WSServillantas.sendVoidedDocumentXmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.retail.efact/TransactionService/sendVoidedDocumentXmlRequest", ReplyAction="http://service.retail.efact/TransactionService/sendVoidedDocumentXmlResponse")]
        System.Threading.Tasks.Task<FE_SERVILLANTAS.WSServillantas.sendVoidedDocumentXmlResponse> sendVoidedDocumentXmlAsync(FE_SERVILLANTAS.WSServillantas.sendVoidedDocumentXmlRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendPing", WrapperNamespace="http://service.retail.efact/", IsWrapped=true)]
    public partial class sendPingRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://service.retail.efact/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FE_SERVILLANTAS.WSServillantas.authorization Authorization;
        
        public sendPingRequest() {
        }
        
        public sendPingRequest(FE_SERVILLANTAS.WSServillantas.authorization Authorization) {
            this.Authorization = Authorization;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendPingResponse", WrapperNamespace="http://service.retail.efact/", IsWrapped=true)]
    public partial class sendPingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FE_SERVILLANTAS.WSServillantas.transactionResponse[] responseSendPing;
        
        public sendPingResponse() {
        }
        
        public sendPingResponse(FE_SERVILLANTAS.WSServillantas.transactionResponse[] responseSendPing) {
            this.responseSendPing = responseSendPing;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendDespatchAdvice", WrapperNamespace="http://service.retail.efact/", IsWrapped=true)]
    public partial class sendDespatchAdviceRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://service.retail.efact/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FE_SERVILLANTAS.WSServillantas.authorization Authorization;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public sendDespatchAdviceRequest() {
        }
        
        public sendDespatchAdviceRequest(FE_SERVILLANTAS.WSServillantas.authorization Authorization, byte[] file) {
            this.Authorization = Authorization;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendDespatchAdviceResponse", WrapperNamespace="http://service.retail.efact/", IsWrapped=true)]
    public partial class sendDespatchAdviceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FE_SERVILLANTAS.WSServillantas.transactionResponse[] responseSendDespatchAdvice;
        
        public sendDespatchAdviceResponse() {
        }
        
        public sendDespatchAdviceResponse(FE_SERVILLANTAS.WSServillantas.transactionResponse[] responseSendDespatchAdvice) {
            this.responseSendDespatchAdvice = responseSendDespatchAdvice;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendInvoice", WrapperNamespace="http://service.retail.efact/", IsWrapped=true)]
    public partial class sendInvoiceRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://service.retail.efact/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FE_SERVILLANTAS.WSServillantas.authorization Authorization;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public sendInvoiceRequest() {
        }
        
        public sendInvoiceRequest(FE_SERVILLANTAS.WSServillantas.authorization Authorization, byte[] file) {
            this.Authorization = Authorization;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendInvoiceResponse", WrapperNamespace="http://service.retail.efact/", IsWrapped=true)]
    public partial class sendInvoiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FE_SERVILLANTAS.WSServillantas.transactionResponse[] responseSendInvoice;
        
        public sendInvoiceResponse() {
        }
        
        public sendInvoiceResponse(FE_SERVILLANTAS.WSServillantas.transactionResponse[] responseSendInvoice) {
            this.responseSendInvoice = responseSendInvoice;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendBoleta", WrapperNamespace="http://service.retail.efact/", IsWrapped=true)]
    public partial class sendBoletaRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://service.retail.efact/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FE_SERVILLANTAS.WSServillantas.authorization Authorization;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public sendBoletaRequest() {
        }
        
        public sendBoletaRequest(FE_SERVILLANTAS.WSServillantas.authorization Authorization, byte[] file) {
            this.Authorization = Authorization;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendBoletaResponse", WrapperNamespace="http://service.retail.efact/", IsWrapped=true)]
    public partial class sendBoletaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FE_SERVILLANTAS.WSServillantas.transactionResponse[] responseSendBoleta;
        
        public sendBoletaResponse() {
        }
        
        public sendBoletaResponse(FE_SERVILLANTAS.WSServillantas.transactionResponse[] responseSendBoleta) {
            this.responseSendBoleta = responseSendBoleta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendCreditNote", WrapperNamespace="http://service.retail.efact/", IsWrapped=true)]
    public partial class sendCreditNoteRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://service.retail.efact/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FE_SERVILLANTAS.WSServillantas.authorization Authorization;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public sendCreditNoteRequest() {
        }
        
        public sendCreditNoteRequest(FE_SERVILLANTAS.WSServillantas.authorization Authorization, byte[] file) {
            this.Authorization = Authorization;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendCreditNoteResponse", WrapperNamespace="http://service.retail.efact/", IsWrapped=true)]
    public partial class sendCreditNoteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FE_SERVILLANTAS.WSServillantas.transactionResponse[] responseSendCreditNote;
        
        public sendCreditNoteResponse() {
        }
        
        public sendCreditNoteResponse(FE_SERVILLANTAS.WSServillantas.transactionResponse[] responseSendCreditNote) {
            this.responseSendCreditNote = responseSendCreditNote;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendDebitNote", WrapperNamespace="http://service.retail.efact/", IsWrapped=true)]
    public partial class sendDebitNoteRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://service.retail.efact/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FE_SERVILLANTAS.WSServillantas.authorization Authorization;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public sendDebitNoteRequest() {
        }
        
        public sendDebitNoteRequest(FE_SERVILLANTAS.WSServillantas.authorization Authorization, byte[] file) {
            this.Authorization = Authorization;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendDebitNoteResponse", WrapperNamespace="http://service.retail.efact/", IsWrapped=true)]
    public partial class sendDebitNoteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FE_SERVILLANTAS.WSServillantas.transactionResponse[] responseSendDebitNote;
        
        public sendDebitNoteResponse() {
        }
        
        public sendDebitNoteResponse(FE_SERVILLANTAS.WSServillantas.transactionResponse[] responseSendDebitNote) {
            this.responseSendDebitNote = responseSendDebitNote;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendVoidedDocument", WrapperNamespace="http://service.retail.efact/", IsWrapped=true)]
    public partial class sendVoidedDocumentRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://service.retail.efact/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FE_SERVILLANTAS.WSServillantas.authorization Authorization;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public sendVoidedDocumentRequest() {
        }
        
        public sendVoidedDocumentRequest(FE_SERVILLANTAS.WSServillantas.authorization Authorization, byte[] file) {
            this.Authorization = Authorization;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendVoidedDocumentResponse", WrapperNamespace="http://service.retail.efact/", IsWrapped=true)]
    public partial class sendVoidedDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FE_SERVILLANTAS.WSServillantas.transactionResponse[] responseVoidedDocument;
        
        public sendVoidedDocumentResponse() {
        }
        
        public sendVoidedDocumentResponse(FE_SERVILLANTAS.WSServillantas.transactionResponse[] responseVoidedDocument) {
            this.responseVoidedDocument = responseVoidedDocument;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendPerception", WrapperNamespace="http://service.retail.efact/", IsWrapped=true)]
    public partial class sendPerceptionRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://service.retail.efact/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FE_SERVILLANTAS.WSServillantas.authorization Authorization;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public sendPerceptionRequest() {
        }
        
        public sendPerceptionRequest(FE_SERVILLANTAS.WSServillantas.authorization Authorization, byte[] file) {
            this.Authorization = Authorization;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendPerceptionResponse", WrapperNamespace="http://service.retail.efact/", IsWrapped=true)]
    public partial class sendPerceptionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FE_SERVILLANTAS.WSServillantas.transactionResponse[] responseSendPerception;
        
        public sendPerceptionResponse() {
        }
        
        public sendPerceptionResponse(FE_SERVILLANTAS.WSServillantas.transactionResponse[] responseSendPerception) {
            this.responseSendPerception = responseSendPerception;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendRetention", WrapperNamespace="http://service.retail.efact/", IsWrapped=true)]
    public partial class sendRetentionRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://service.retail.efact/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FE_SERVILLANTAS.WSServillantas.authorization Authorization;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public sendRetentionRequest() {
        }
        
        public sendRetentionRequest(FE_SERVILLANTAS.WSServillantas.authorization Authorization, byte[] file) {
            this.Authorization = Authorization;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendRetentionResponse", WrapperNamespace="http://service.retail.efact/", IsWrapped=true)]
    public partial class sendRetentionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FE_SERVILLANTAS.WSServillantas.transactionResponse[] responseSendRetention;
        
        public sendRetentionResponse() {
        }
        
        public sendRetentionResponse(FE_SERVILLANTAS.WSServillantas.transactionResponse[] responseSendRetention) {
            this.responseSendRetention = responseSendRetention;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.retail.efact/")]
    public partial class transactionResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] cdrFileField;
        
        private string digestValueField;
        
        private string identifierField;
        
        private string messageField;
        
        private string outStringField;
        
        private byte[] pdfFileField;
        
        private string statusField;
        
        private byte[] xmlSignedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] cdrFile {
            get {
                return this.cdrFileField;
            }
            set {
                this.cdrFileField = value;
                this.RaisePropertyChanged("cdrFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string digestValue {
            get {
                return this.digestValueField;
            }
            set {
                this.digestValueField = value;
                this.RaisePropertyChanged("digestValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
                this.RaisePropertyChanged("identifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string outString {
            get {
                return this.outStringField;
            }
            set {
                this.outStringField = value;
                this.RaisePropertyChanged("outString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=5)]
        public byte[] pdfFile {
            get {
                return this.pdfFileField;
            }
            set {
                this.pdfFileField = value;
                this.RaisePropertyChanged("pdfFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=7)]
        public byte[] xmlSigned {
            get {
                return this.xmlSignedField;
            }
            set {
                this.xmlSignedField = value;
                this.RaisePropertyChanged("xmlSigned");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStatus", WrapperNamespace="http://service.retail.efact/", IsWrapped=true)]
    public partial class getStatusRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://service.retail.efact/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FE_SERVILLANTAS.WSServillantas.authorization Authorization;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int documentType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string identifier;
        
        public getStatusRequest() {
        }
        
        public getStatusRequest(FE_SERVILLANTAS.WSServillantas.authorization Authorization, int documentType, string identifier) {
            this.Authorization = Authorization;
            this.documentType = documentType;
            this.identifier = identifier;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStatusResponse", WrapperNamespace="http://service.retail.efact/", IsWrapped=true)]
    public partial class getStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public FE_SERVILLANTAS.WSServillantas.transactionResult responseGetStatus;
        
        public getStatusResponse() {
        }
        
        public getStatusResponse(FE_SERVILLANTAS.WSServillantas.transactionResult responseGetStatus) {
            this.responseGetStatus = responseGetStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendVoidedDocumentXml", WrapperNamespace="http://service.retail.efact/", IsWrapped=true)]
    public partial class sendVoidedDocumentXmlRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://service.retail.efact/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FE_SERVILLANTAS.WSServillantas.authorization Authorization;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public sendVoidedDocumentXmlRequest() {
        }
        
        public sendVoidedDocumentXmlRequest(FE_SERVILLANTAS.WSServillantas.authorization Authorization, byte[] file) {
            this.Authorization = Authorization;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendVoidedDocumentXmlResponse", WrapperNamespace="http://service.retail.efact/", IsWrapped=true)]
    public partial class sendVoidedDocumentXmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FE_SERVILLANTAS.WSServillantas.transactionResponse[] responseVoidedDocumentXml;
        
        public sendVoidedDocumentXmlResponse() {
        }
        
        public sendVoidedDocumentXmlResponse(FE_SERVILLANTAS.WSServillantas.transactionResponse[] responseVoidedDocumentXml) {
            this.responseVoidedDocumentXml = responseVoidedDocumentXml;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TransactionServiceChannel : FE_SERVILLANTAS.WSServillantas.TransactionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransactionServiceClient : System.ServiceModel.ClientBase<FE_SERVILLANTAS.WSServillantas.TransactionService>, FE_SERVILLANTAS.WSServillantas.TransactionService {
        
        public TransactionServiceClient() {
        }
        
        public TransactionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransactionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransactionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransactionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FE_SERVILLANTAS.WSServillantas.sendPingResponse FE_SERVILLANTAS.WSServillantas.TransactionService.sendPing(FE_SERVILLANTAS.WSServillantas.sendPingRequest request) {
            return base.Channel.sendPing(request);
        }
        
        public FE_SERVILLANTAS.WSServillantas.transactionResponse[] sendPing(FE_SERVILLANTAS.WSServillantas.authorization Authorization) {
            FE_SERVILLANTAS.WSServillantas.sendPingRequest inValue = new FE_SERVILLANTAS.WSServillantas.sendPingRequest();
            inValue.Authorization = Authorization;
            FE_SERVILLANTAS.WSServillantas.sendPingResponse retVal = ((FE_SERVILLANTAS.WSServillantas.TransactionService)(this)).sendPing(inValue);
            return retVal.responseSendPing;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FE_SERVILLANTAS.WSServillantas.sendPingResponse> FE_SERVILLANTAS.WSServillantas.TransactionService.sendPingAsync(FE_SERVILLANTAS.WSServillantas.sendPingRequest request) {
            return base.Channel.sendPingAsync(request);
        }
        
        public System.Threading.Tasks.Task<FE_SERVILLANTAS.WSServillantas.sendPingResponse> sendPingAsync(FE_SERVILLANTAS.WSServillantas.authorization Authorization) {
            FE_SERVILLANTAS.WSServillantas.sendPingRequest inValue = new FE_SERVILLANTAS.WSServillantas.sendPingRequest();
            inValue.Authorization = Authorization;
            return ((FE_SERVILLANTAS.WSServillantas.TransactionService)(this)).sendPingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FE_SERVILLANTAS.WSServillantas.sendDespatchAdviceResponse FE_SERVILLANTAS.WSServillantas.TransactionService.sendDespatchAdvice(FE_SERVILLANTAS.WSServillantas.sendDespatchAdviceRequest request) {
            return base.Channel.sendDespatchAdvice(request);
        }
        
        public FE_SERVILLANTAS.WSServillantas.transactionResponse[] sendDespatchAdvice(FE_SERVILLANTAS.WSServillantas.authorization Authorization, byte[] file) {
            FE_SERVILLANTAS.WSServillantas.sendDespatchAdviceRequest inValue = new FE_SERVILLANTAS.WSServillantas.sendDespatchAdviceRequest();
            inValue.Authorization = Authorization;
            inValue.file = file;
            FE_SERVILLANTAS.WSServillantas.sendDespatchAdviceResponse retVal = ((FE_SERVILLANTAS.WSServillantas.TransactionService)(this)).sendDespatchAdvice(inValue);
            return retVal.responseSendDespatchAdvice;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FE_SERVILLANTAS.WSServillantas.sendDespatchAdviceResponse> FE_SERVILLANTAS.WSServillantas.TransactionService.sendDespatchAdviceAsync(FE_SERVILLANTAS.WSServillantas.sendDespatchAdviceRequest request) {
            return base.Channel.sendDespatchAdviceAsync(request);
        }
        
        public System.Threading.Tasks.Task<FE_SERVILLANTAS.WSServillantas.sendDespatchAdviceResponse> sendDespatchAdviceAsync(FE_SERVILLANTAS.WSServillantas.authorization Authorization, byte[] file) {
            FE_SERVILLANTAS.WSServillantas.sendDespatchAdviceRequest inValue = new FE_SERVILLANTAS.WSServillantas.sendDespatchAdviceRequest();
            inValue.Authorization = Authorization;
            inValue.file = file;
            return ((FE_SERVILLANTAS.WSServillantas.TransactionService)(this)).sendDespatchAdviceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FE_SERVILLANTAS.WSServillantas.sendInvoiceResponse FE_SERVILLANTAS.WSServillantas.TransactionService.sendInvoice(FE_SERVILLANTAS.WSServillantas.sendInvoiceRequest request) {
            return base.Channel.sendInvoice(request);
        }
        
        public FE_SERVILLANTAS.WSServillantas.transactionResponse[] sendInvoice(FE_SERVILLANTAS.WSServillantas.authorization Authorization, byte[] file) {
            FE_SERVILLANTAS.WSServillantas.sendInvoiceRequest inValue = new FE_SERVILLANTAS.WSServillantas.sendInvoiceRequest();
            inValue.Authorization = Authorization;
            inValue.file = file;
            FE_SERVILLANTAS.WSServillantas.sendInvoiceResponse retVal = ((FE_SERVILLANTAS.WSServillantas.TransactionService)(this)).sendInvoice(inValue);
            return retVal.responseSendInvoice;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FE_SERVILLANTAS.WSServillantas.sendInvoiceResponse> FE_SERVILLANTAS.WSServillantas.TransactionService.sendInvoiceAsync(FE_SERVILLANTAS.WSServillantas.sendInvoiceRequest request) {
            return base.Channel.sendInvoiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<FE_SERVILLANTAS.WSServillantas.sendInvoiceResponse> sendInvoiceAsync(FE_SERVILLANTAS.WSServillantas.authorization Authorization, byte[] file) {
            FE_SERVILLANTAS.WSServillantas.sendInvoiceRequest inValue = new FE_SERVILLANTAS.WSServillantas.sendInvoiceRequest();
            inValue.Authorization = Authorization;
            inValue.file = file;
            return ((FE_SERVILLANTAS.WSServillantas.TransactionService)(this)).sendInvoiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FE_SERVILLANTAS.WSServillantas.sendBoletaResponse FE_SERVILLANTAS.WSServillantas.TransactionService.sendBoleta(FE_SERVILLANTAS.WSServillantas.sendBoletaRequest request) {
            return base.Channel.sendBoleta(request);
        }
        
        public FE_SERVILLANTAS.WSServillantas.transactionResponse[] sendBoleta(FE_SERVILLANTAS.WSServillantas.authorization Authorization, byte[] file) {
            FE_SERVILLANTAS.WSServillantas.sendBoletaRequest inValue = new FE_SERVILLANTAS.WSServillantas.sendBoletaRequest();
            inValue.Authorization = Authorization;
            inValue.file = file;
            FE_SERVILLANTAS.WSServillantas.sendBoletaResponse retVal = ((FE_SERVILLANTAS.WSServillantas.TransactionService)(this)).sendBoleta(inValue);
            return retVal.responseSendBoleta;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FE_SERVILLANTAS.WSServillantas.sendBoletaResponse> FE_SERVILLANTAS.WSServillantas.TransactionService.sendBoletaAsync(FE_SERVILLANTAS.WSServillantas.sendBoletaRequest request) {
            return base.Channel.sendBoletaAsync(request);
        }
        
        public System.Threading.Tasks.Task<FE_SERVILLANTAS.WSServillantas.sendBoletaResponse> sendBoletaAsync(FE_SERVILLANTAS.WSServillantas.authorization Authorization, byte[] file) {
            FE_SERVILLANTAS.WSServillantas.sendBoletaRequest inValue = new FE_SERVILLANTAS.WSServillantas.sendBoletaRequest();
            inValue.Authorization = Authorization;
            inValue.file = file;
            return ((FE_SERVILLANTAS.WSServillantas.TransactionService)(this)).sendBoletaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FE_SERVILLANTAS.WSServillantas.sendCreditNoteResponse FE_SERVILLANTAS.WSServillantas.TransactionService.sendCreditNote(FE_SERVILLANTAS.WSServillantas.sendCreditNoteRequest request) {
            return base.Channel.sendCreditNote(request);
        }
        
        public FE_SERVILLANTAS.WSServillantas.transactionResponse[] sendCreditNote(FE_SERVILLANTAS.WSServillantas.authorization Authorization, byte[] file) {
            FE_SERVILLANTAS.WSServillantas.sendCreditNoteRequest inValue = new FE_SERVILLANTAS.WSServillantas.sendCreditNoteRequest();
            inValue.Authorization = Authorization;
            inValue.file = file;
            FE_SERVILLANTAS.WSServillantas.sendCreditNoteResponse retVal = ((FE_SERVILLANTAS.WSServillantas.TransactionService)(this)).sendCreditNote(inValue);
            return retVal.responseSendCreditNote;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FE_SERVILLANTAS.WSServillantas.sendCreditNoteResponse> FE_SERVILLANTAS.WSServillantas.TransactionService.sendCreditNoteAsync(FE_SERVILLANTAS.WSServillantas.sendCreditNoteRequest request) {
            return base.Channel.sendCreditNoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<FE_SERVILLANTAS.WSServillantas.sendCreditNoteResponse> sendCreditNoteAsync(FE_SERVILLANTAS.WSServillantas.authorization Authorization, byte[] file) {
            FE_SERVILLANTAS.WSServillantas.sendCreditNoteRequest inValue = new FE_SERVILLANTAS.WSServillantas.sendCreditNoteRequest();
            inValue.Authorization = Authorization;
            inValue.file = file;
            return ((FE_SERVILLANTAS.WSServillantas.TransactionService)(this)).sendCreditNoteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FE_SERVILLANTAS.WSServillantas.sendDebitNoteResponse FE_SERVILLANTAS.WSServillantas.TransactionService.sendDebitNote(FE_SERVILLANTAS.WSServillantas.sendDebitNoteRequest request) {
            return base.Channel.sendDebitNote(request);
        }
        
        public FE_SERVILLANTAS.WSServillantas.transactionResponse[] sendDebitNote(FE_SERVILLANTAS.WSServillantas.authorization Authorization, byte[] file) {
            FE_SERVILLANTAS.WSServillantas.sendDebitNoteRequest inValue = new FE_SERVILLANTAS.WSServillantas.sendDebitNoteRequest();
            inValue.Authorization = Authorization;
            inValue.file = file;
            FE_SERVILLANTAS.WSServillantas.sendDebitNoteResponse retVal = ((FE_SERVILLANTAS.WSServillantas.TransactionService)(this)).sendDebitNote(inValue);
            return retVal.responseSendDebitNote;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FE_SERVILLANTAS.WSServillantas.sendDebitNoteResponse> FE_SERVILLANTAS.WSServillantas.TransactionService.sendDebitNoteAsync(FE_SERVILLANTAS.WSServillantas.sendDebitNoteRequest request) {
            return base.Channel.sendDebitNoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<FE_SERVILLANTAS.WSServillantas.sendDebitNoteResponse> sendDebitNoteAsync(FE_SERVILLANTAS.WSServillantas.authorization Authorization, byte[] file) {
            FE_SERVILLANTAS.WSServillantas.sendDebitNoteRequest inValue = new FE_SERVILLANTAS.WSServillantas.sendDebitNoteRequest();
            inValue.Authorization = Authorization;
            inValue.file = file;
            return ((FE_SERVILLANTAS.WSServillantas.TransactionService)(this)).sendDebitNoteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FE_SERVILLANTAS.WSServillantas.sendVoidedDocumentResponse FE_SERVILLANTAS.WSServillantas.TransactionService.sendVoidedDocument(FE_SERVILLANTAS.WSServillantas.sendVoidedDocumentRequest request) {
            return base.Channel.sendVoidedDocument(request);
        }
        
        public FE_SERVILLANTAS.WSServillantas.transactionResponse[] sendVoidedDocument(FE_SERVILLANTAS.WSServillantas.authorization Authorization, byte[] file) {
            FE_SERVILLANTAS.WSServillantas.sendVoidedDocumentRequest inValue = new FE_SERVILLANTAS.WSServillantas.sendVoidedDocumentRequest();
            inValue.Authorization = Authorization;
            inValue.file = file;
            FE_SERVILLANTAS.WSServillantas.sendVoidedDocumentResponse retVal = ((FE_SERVILLANTAS.WSServillantas.TransactionService)(this)).sendVoidedDocument(inValue);
            return retVal.responseVoidedDocument;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FE_SERVILLANTAS.WSServillantas.sendVoidedDocumentResponse> FE_SERVILLANTAS.WSServillantas.TransactionService.sendVoidedDocumentAsync(FE_SERVILLANTAS.WSServillantas.sendVoidedDocumentRequest request) {
            return base.Channel.sendVoidedDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<FE_SERVILLANTAS.WSServillantas.sendVoidedDocumentResponse> sendVoidedDocumentAsync(FE_SERVILLANTAS.WSServillantas.authorization Authorization, byte[] file) {
            FE_SERVILLANTAS.WSServillantas.sendVoidedDocumentRequest inValue = new FE_SERVILLANTAS.WSServillantas.sendVoidedDocumentRequest();
            inValue.Authorization = Authorization;
            inValue.file = file;
            return ((FE_SERVILLANTAS.WSServillantas.TransactionService)(this)).sendVoidedDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FE_SERVILLANTAS.WSServillantas.sendPerceptionResponse FE_SERVILLANTAS.WSServillantas.TransactionService.sendPerception(FE_SERVILLANTAS.WSServillantas.sendPerceptionRequest request) {
            return base.Channel.sendPerception(request);
        }
        
        public FE_SERVILLANTAS.WSServillantas.transactionResponse[] sendPerception(FE_SERVILLANTAS.WSServillantas.authorization Authorization, byte[] file) {
            FE_SERVILLANTAS.WSServillantas.sendPerceptionRequest inValue = new FE_SERVILLANTAS.WSServillantas.sendPerceptionRequest();
            inValue.Authorization = Authorization;
            inValue.file = file;
            FE_SERVILLANTAS.WSServillantas.sendPerceptionResponse retVal = ((FE_SERVILLANTAS.WSServillantas.TransactionService)(this)).sendPerception(inValue);
            return retVal.responseSendPerception;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FE_SERVILLANTAS.WSServillantas.sendPerceptionResponse> FE_SERVILLANTAS.WSServillantas.TransactionService.sendPerceptionAsync(FE_SERVILLANTAS.WSServillantas.sendPerceptionRequest request) {
            return base.Channel.sendPerceptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<FE_SERVILLANTAS.WSServillantas.sendPerceptionResponse> sendPerceptionAsync(FE_SERVILLANTAS.WSServillantas.authorization Authorization, byte[] file) {
            FE_SERVILLANTAS.WSServillantas.sendPerceptionRequest inValue = new FE_SERVILLANTAS.WSServillantas.sendPerceptionRequest();
            inValue.Authorization = Authorization;
            inValue.file = file;
            return ((FE_SERVILLANTAS.WSServillantas.TransactionService)(this)).sendPerceptionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FE_SERVILLANTAS.WSServillantas.sendRetentionResponse FE_SERVILLANTAS.WSServillantas.TransactionService.sendRetention(FE_SERVILLANTAS.WSServillantas.sendRetentionRequest request) {
            return base.Channel.sendRetention(request);
        }
        
        public FE_SERVILLANTAS.WSServillantas.transactionResponse[] sendRetention(FE_SERVILLANTAS.WSServillantas.authorization Authorization, byte[] file) {
            FE_SERVILLANTAS.WSServillantas.sendRetentionRequest inValue = new FE_SERVILLANTAS.WSServillantas.sendRetentionRequest();
            inValue.Authorization = Authorization;
            inValue.file = file;
            FE_SERVILLANTAS.WSServillantas.sendRetentionResponse retVal = ((FE_SERVILLANTAS.WSServillantas.TransactionService)(this)).sendRetention(inValue);
            return retVal.responseSendRetention;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FE_SERVILLANTAS.WSServillantas.sendRetentionResponse> FE_SERVILLANTAS.WSServillantas.TransactionService.sendRetentionAsync(FE_SERVILLANTAS.WSServillantas.sendRetentionRequest request) {
            return base.Channel.sendRetentionAsync(request);
        }
        
        public System.Threading.Tasks.Task<FE_SERVILLANTAS.WSServillantas.sendRetentionResponse> sendRetentionAsync(FE_SERVILLANTAS.WSServillantas.authorization Authorization, byte[] file) {
            FE_SERVILLANTAS.WSServillantas.sendRetentionRequest inValue = new FE_SERVILLANTAS.WSServillantas.sendRetentionRequest();
            inValue.Authorization = Authorization;
            inValue.file = file;
            return ((FE_SERVILLANTAS.WSServillantas.TransactionService)(this)).sendRetentionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FE_SERVILLANTAS.WSServillantas.getStatusResponse FE_SERVILLANTAS.WSServillantas.TransactionService.getStatus(FE_SERVILLANTAS.WSServillantas.getStatusRequest request) {
            return base.Channel.getStatus(request);
        }
        
        public FE_SERVILLANTAS.WSServillantas.transactionResult getStatus(FE_SERVILLANTAS.WSServillantas.authorization Authorization, int documentType, string identifier) {
            FE_SERVILLANTAS.WSServillantas.getStatusRequest inValue = new FE_SERVILLANTAS.WSServillantas.getStatusRequest();
            inValue.Authorization = Authorization;
            inValue.documentType = documentType;
            inValue.identifier = identifier;
            FE_SERVILLANTAS.WSServillantas.getStatusResponse retVal = ((FE_SERVILLANTAS.WSServillantas.TransactionService)(this)).getStatus(inValue);
            return retVal.responseGetStatus;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FE_SERVILLANTAS.WSServillantas.getStatusResponse> FE_SERVILLANTAS.WSServillantas.TransactionService.getStatusAsync(FE_SERVILLANTAS.WSServillantas.getStatusRequest request) {
            return base.Channel.getStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<FE_SERVILLANTAS.WSServillantas.getStatusResponse> getStatusAsync(FE_SERVILLANTAS.WSServillantas.authorization Authorization, int documentType, string identifier) {
            FE_SERVILLANTAS.WSServillantas.getStatusRequest inValue = new FE_SERVILLANTAS.WSServillantas.getStatusRequest();
            inValue.Authorization = Authorization;
            inValue.documentType = documentType;
            inValue.identifier = identifier;
            return ((FE_SERVILLANTAS.WSServillantas.TransactionService)(this)).getStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FE_SERVILLANTAS.WSServillantas.sendVoidedDocumentXmlResponse FE_SERVILLANTAS.WSServillantas.TransactionService.sendVoidedDocumentXml(FE_SERVILLANTAS.WSServillantas.sendVoidedDocumentXmlRequest request) {
            return base.Channel.sendVoidedDocumentXml(request);
        }
        
        public FE_SERVILLANTAS.WSServillantas.transactionResponse[] sendVoidedDocumentXml(FE_SERVILLANTAS.WSServillantas.authorization Authorization, byte[] file) {
            FE_SERVILLANTAS.WSServillantas.sendVoidedDocumentXmlRequest inValue = new FE_SERVILLANTAS.WSServillantas.sendVoidedDocumentXmlRequest();
            inValue.Authorization = Authorization;
            inValue.file = file;
            FE_SERVILLANTAS.WSServillantas.sendVoidedDocumentXmlResponse retVal = ((FE_SERVILLANTAS.WSServillantas.TransactionService)(this)).sendVoidedDocumentXml(inValue);
            return retVal.responseVoidedDocumentXml;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FE_SERVILLANTAS.WSServillantas.sendVoidedDocumentXmlResponse> FE_SERVILLANTAS.WSServillantas.TransactionService.sendVoidedDocumentXmlAsync(FE_SERVILLANTAS.WSServillantas.sendVoidedDocumentXmlRequest request) {
            return base.Channel.sendVoidedDocumentXmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<FE_SERVILLANTAS.WSServillantas.sendVoidedDocumentXmlResponse> sendVoidedDocumentXmlAsync(FE_SERVILLANTAS.WSServillantas.authorization Authorization, byte[] file) {
            FE_SERVILLANTAS.WSServillantas.sendVoidedDocumentXmlRequest inValue = new FE_SERVILLANTAS.WSServillantas.sendVoidedDocumentXmlRequest();
            inValue.Authorization = Authorization;
            inValue.file = file;
            return ((FE_SERVILLANTAS.WSServillantas.TransactionService)(this)).sendVoidedDocumentXmlAsync(inValue);
        }
    }
}
